services:

  postgres:
    image: postgres:16-alpine
    container_name: aidaptive-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aidaptive
      - POSTGRES_PASSWORD=aidaptive2024
      - POSTGRES_DB=aidaptive_benchmark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidaptive"]
      interval: 5s
      timeout: 5s
      retries: 5

  influxdb:
    image: influxdb:2.7
    container_name: aidaptive-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=aidaptive2024
      - DOCKER_INFLUXDB_INIT_ORG=aidaptive
      - DOCKER_INFLUXDB_INIT_BUCKET=benchmarks
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=aidaptive-benchmark-token
    volumes:
      - influxdb_data:/var/lib/influxdb2



volumes:
  postgres_data:
  influxdb_data:
